spring:
  application:
    name: MdToWord
  # 添加数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springvue_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 2000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 2000

# 自定义文件上传配置
file:
  upload:
    path: ./uploads/avatars/  # 头像文件存储路径
    max-size: 104857600  # 最大文件大小（100MB）

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启SQL日志
    map-underscore-to-camel-case: true # 开启驼峰命名
  global-config:
    db-config:
      id-type: auto # 主键自增策略
      table-prefix: tb_ # 表前缀

# JWT配置
jwt:
  secret: myVeryLongSecretKeyThatIsAtLeast256BitsLongForProductionUse
  expiration: 86400  # 24小时，单位：秒

logging:
  level:
    com.example.mdtoword: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Redis配置（用于单点登录）

# SSO配置
sso:
  enabled: true
  key-prefix: sso:token